name: nectar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # Logic
  dartzmq: ^1.0.0-dev.17 # To talk to nestd
  provider: ^6.0.0       # State management
  intl: ^0.18.0          # Dates/Time
  path_provider: ^2.0.0  # File paths
  uuid: ^4.0.0

  # Media
  file_picker: ^6.0.0    # Upload files
  record: ^6.1.2         # Voice Recorder
  audioplayers: ^5.0.0   # Voice Player
  video_player: ^2.8.0   # Video Player
  chewie: ^1.7.0         # UI wrapper for video player
  flutter_markdown: ^0.6.0 # For rich text

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
